"""Add mqtt_password to devices"""
import sqlalchemy as sa
from alembic import op

revision = '8c5a1813525a'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('mqtt_password', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'mqtt_password')
    # ### end Alembic commands ###
