"""add unit to parameters"""
from alembic import op
import sqlalchemy as sa


revision = 'b6f395ec384a'
down_revision = '8c5a1813525a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameters', sa.Column('unit', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameters', 'unit')
    # ### end Alembic commands ###
